version: "3.6"

volumes:
  cargo_home:

services:
  rustdev:
    image: kimyvgy/rustdev:1-bullseye
    working_dir: /app
    volumes:
      - cargo_home:/usr/local/cargo
      - ../:/app
    environment:
      UID: ${UID}
      GID: ${GID}
    tty: true
