name: "Debian"

on:
  pull_request:
    paths:
      - debian/**
  push:
    paths:
      - debian/**

jobs:
  docker:
    name: ${{matrix.version}}-${{matrix.distro}}
    runs-on: ubuntu:latest
    strategy:
      matrix:
        version: ["1.70", "1.71"]
        distro: ["buster", "bullseye"]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
