name: "Debian"

on:
  pull_request:
    paths:
      - .github/workflows/debian.yml
      - debian/**
  push:
    paths:
      - .github/workflows/debian.yml
      - debian/**

jobs:
  docker:
    name: ${{matrix.version}}-${{matrix.distro}}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version: ["1", "1.71"]
        distro:
          [
            "buster",
            "slim-buster",
            "bullseye",
            "slim-bullseye",
            "bookworm",
            "slim-bookworm",
          ]
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: "{{defaultContext}}:debian"
          push: true
          tags: kimyvgy/rustdev:${{matrix.version}}-${{matrix.distro}}
          cache-from: type=registry,ref=kimyvgy/rustdev:${{matrix.version}}-${{matrix.distro}}
